In [2]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
type(L[0])

int

In [4]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [5]:
type(L2[0])

str

In [7]:
L3 =[True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [9]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
import numpy as np
#integer array
np.array([1,4,2,5,13])

array([ 1,  4,  2,  5, 13])

In [11]:
#numpy will upcast types i.e. convert int to float if possible
np.array([3.14, 4, 2, 3])

array([ 3.14,  4.  ,  2.  ,  3.  ])

In [12]:
#explicity telling what type
np.array([1,2,3,4], dtype = 'float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [13]:
#multidim array using a list of list.
np.array([range(i, i+3)for i in (2,4,6)])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
# create a length-10 integer array filled with zeros
np.zeros(10, dtype =int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
# create a 3x5 floating-point array filled with ones
np.ones((3,5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [16]:
# create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [17]:
# Create an array filled with a linear sequence
# starting at 0, ending at 20, stepppign by 2
# (this is simliary to the built-in range() function)
np.arange(0,20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [20]:
# Create a 3x3 array of unifmorly distrbuted
# random values between 0 and 1
np.random.random((3,3))

array([[ 0.90909177,  0.48719295,  0.67676938],
       [ 0.98549785,  0.32180236,  0.0278472 ],
       [ 0.61704987,  0.72560042,  0.5282799 ]])

In [22]:
# create a 3x3 array of normally distributed random values
# with mean 0, and standard deviation 1
np.random.normal(0,1, (3,3))

array([[ 1.02104022, -0.12765118,  2.69141583],
       [-0.71757678, -0.2661858 ,  2.22100933],
       [ 1.80769047, -0.13081301,  1.28692601]])

In [25]:
# crate a 3x3 array of random integers in the interval [0 , 10]
np.random.randint(0, 10, (3,3))

array([[5, 2, 3],
       [8, 2, 4],
       [9, 6, 5]])

In [26]:
# create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [27]:
# craete an uninitialized array of three integers
# the values will be whatever happens to already exist at the memory location
np.empty(3)

array([ 1.,  1.,  1.])